#!/usr/local/bin/bash

# Flags, anyone?
arg1=$1
arg2=$2

DB_DATABASE=allotment
#DB_USERNAME=root
#DB_PASSWORD="#!M31chiz3"
DB_USERNAME=allotuser
DB_PASSWORD="x5rtg4ybX!@"

function loadFreshData {
    echo "Refreshing the data...";
    mysql -u $DB_USERNAME -p$DB_PASSWORD $DB_DATABASE < allotClean.sql

    # Clean up error reporting
    cat /dev/null > rolloverExceptions
}


function helpmenu {
    echo "This runs the available test cases by invoking artisan test (with or without flags).\n"
    echo "Options include:\n"
    echo "-h or --help  -- This menu\n"
    echo "-c or --coverage -- Run tests with coverage data\n"
    echo "-v or --verbose -- Runs tests with verbose output.\n"
}


test "$arg1" == "-h" && helpmenu; exit;

loadFreshMenu 
test "$arg1" == "-c" && ./artisan test --coverage exit;
test "$arg1" == "-v" && ./artisan test -v exit;

./artisan test



